language: php
sudo: true

php:
  - 5.6

git:
  depth: 1

matrix:
#  allow_failures:
#    - php: hhvm
  # Don't wait for the allowed failures to build.
  fast_finish: true


# Cache Composer directory so that we don't have to download drush all the time.
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.phantomjs

mysql:
  database: drupal
  username: root
  encoding: utf8

env:
  matrix:
#    - DRUPAL_VERSION='8.1.x'
    - DRUPAL_VERSION='8.3.x' DB='mysql' SIMPLETEST_DB="$DB://root:@127.0.0.1/drupal" DB_USER='root'
  global:
    - SIMPLETEST_BASE_URL=http://127.0.0.1:8888
    - MODULE_NAME='dynamic_entity_reference'
    - MODULE_TEST_GROUP='dynamic_entity_reference'
    - DRUPAL_REPO='git://drupalcode.org/project/drupal.git'
    - DRUSH_VERSION='~8.0'
    - CODER_VERSION='~8.2'

before_install:
  # Disable XDebug to speed up execution.
  - phpenv config-rm xdebug.ini
  - make phantomjs-install

install:
  - make init

before_script:
  - make mkdirs
#  - make make SIMPLETEST_DB=$SIMPLETEST_DB DB_USER=$DB_USER
#  - make install SIMPLETEST_DB=$SIMPLETEST_DB
  - make phantomjs-stop
  - make run-server
  - make phantomjs-start

script:
  - make ci-lint
  - make ci-test APP_URI=$SIMPLETEST_BASE_URL TYPES="PHPUnit-Kernel"
  - make ci-test APP_URI=$SIMPLETEST_BASE_URL TYPES="PHPUnit-Functional"
  - make ci-test APP_URI=$SIMPLETEST_BASE_URL TYPES="PHPUnit-FunctionalJavascript"

after_script:
  - make phantomjs-stop

after_failure:
  - echo "Failures detected. Outputing additional logs:"
  - cat ~/localhost.txt
  - cat ~/phantomjs.txt
