# Schema for the configuration files of the Dynamic Entity Reference module.

field.dynamic_entity_reference.storage_settings:
  type: mapping
  label: 'Dynamic entity reference settings'
  mapping:
    target_type:
      type: string
      label: 'Type of item to reference'
    exclude_entity_types:
      type: boolean
      label: 'Exclude the selected items'
    entity_type_ids:
      type: sequence
      label: 'Entity Type IDs'
      sequence:
        - type: string
          label: 'Entity Type ID'

field.dynamic_entity_reference.field_settings:
  type: mapping
  label: 'Dynamic entity reference settings'
  mapping:
    handler:
      type: string
      label: 'Reference method'
    handler_settings:
      type: entity_reference.[%parent.handler].handler_settings
      label: 'Reference method settings'

field.dynamic_entity_reference.value:
  type: sequence
  label: 'Default value'
  sequence:
    - type: mapping
      label: 'Values'
      mapping:
        target_id:
          type: string
          label: 'Entity ID'
        target_type:
          type: string
          label: 'Type of item to reference'

entity_view_display.field.dynamic_entity_reference_entity_view:
  type: entity_field_view_display_base
  label: 'Entity reference rendered entity display format settings'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        view_mode:
          type: string
          label: 'View mode'
        link:
          type: boolean
          label: 'Show links'

entity_view_display.field.dynamic_entity_reference_entity_id:
  type: entity_field_view_display_base
  label: 'Entity reference entity ID display format settings'
  mapping:
    settings:
      type: sequence
      label: 'Settings'
      sequence:
        - type: string

entity_view_display.field.dynamic_entity_reference_label:
  type: entity_field_view_display_base
  label: 'Dynamic entity reference label display format settings'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        link:
          type: boolean
          label: 'Link label to the referenced entity'

entity_form_display.field.entity_reference_autocomplete_tags:
  type: entity_field_form_display_base
  label: 'Entity reference autocomplete (Tags style) display format settings'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        match_operator:
          type: string
          label: 'Autocomplete matching'
        size:
          type: integer
          label: 'Size of textfield'
        autocomplete_type:
          type: string
          label: 'Autocomplete type'
        placeholder:
          type: label
          label: 'Placeholder'

entity_form_display.field.dynamic_entity_reference_default:
  type: entity_field_form_display_base
  label: 'Dynamic entity reference autocomplete display format settings'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        match_operator:
          type: string
          label: 'Autocomplete matching'
        size:
          type: integer
          label: 'Size of textfield'
        autocomplete_type:
          type: string
          label: 'Autocomplete type'
        placeholder:
          type: label
          label: 'Placeholder'
